import { Character } from "./types";

export const CHARACTERS: Character[] = [
  {
    id: "goku",
    name: "Son Goku",
    series: "Dragon Ball Z",
    role: "The legendary Saiyan protector of Earth",
    blurb: "Driven by an insatiable desire to surpass his limits, Goku seeks out the universe's ultimate fighters. Rising from a low-class Saiyan infant to a god-slayer, he stands as anime's eternal champion of hope and martial arts.",
    themeColor: "#FF5E00",
    motif: "悟",
    stats: {
      power: 99,
      speed: 97,
      technique: 94,
      popularity: 98,
    },
    img: "/src/assets/images/goku_saiyan_1781362594916.jpg",
    crestSymbol: "SAIYAN",
  },
  {
    id: "gojo",
    name: "Satoru Gojo",
    series: "Jujutsu Kaisen",
    role: "The Limitless Six Eyes special-grade sorcerer",
    blurb: "Holder of the Limitless technique and the Six Eyes, Gojo is an absolute anomaly whose existence upended the supernatural balance. Blindfolded yet all-seeing, he casually manipulates space, gravity, and infinity.",
    themeColor: "#06B6D4",
    motif: "無",
    stats: {
      power: 98,
      speed: 98,
      technique: 99,
      popularity: 99,
    },
    img: "/src/assets/images/gojo_eyes_1781362614042.jpg",
    crestSymbol: "LIMITLESS",
  },
  {
    id: "zoro",
    name: "Roronoa Zoro",
    series: "One Piece",
    role: "The Three-Sword Style first mate & master swordsman",
    blurb: "Driven by a vow to become the World's Greatest Swordsman, Zoro steps onto the battlefield wielding katanas in both hands and a third clenched in his teeth. His unyielding spirit and demonic blade cuts through steel and fate alike.",
    themeColor: "#10B981",
    motif: "斬",
    stats: {
      power: 95,
      speed: 92,
      technique: 96,
      popularity: 97,
    },
    img: "/src/assets/images/zoro_swords_1781362632986.jpg",
    crestSymbol: "DEMON",
  },
  {
    id: "killua",
    name: "Killua Zoldyck",
    series: "Hunter x Hunter",
    role: "The lightning-fast, godspeed prodigy assassin",
    blurb: "Bred in darkness to be the perfect assassin, Killua broke away from his family's shadow to forge his own path. Transmuting his aura into high-voltage electricity, he achieves 'Godspeed' state, unleashing kinetic velocity.",
    themeColor: "#8B5CF6",
    motif: "雷",
    stats: {
      power: 89,
      speed: 96,
      technique: 94,
      popularity: 95,
    },
    img: "/src/assets/images/lightning_rogue_1781360253853.jpg",
    crestSymbol: "GODSPEED",
  },
  {
    id: "luffy",
    name: "Monkey D. Luffy",
    series: "One Piece",
    role: "The Straw Hat captain seeking liberated joy",
    blurb: "A rubber-bodied visionary who seeks the treasure of One Piece, not for conquest, but to achieve absolute freedom on the seas. With Gear 5 activated, his battles turn into a cartoonish playground of joy and godlike power.",
    themeColor: "#EF4444",
    motif: "王",
    stats: {
      power: 97,
      speed: 95,
      technique: 91,
      popularity: 98,
    },
    img: "/src/assets/images/luffy_gear5_1781361743055.jpg",
    crestSymbol: "LIBERTY",
  },
  {
    id: "naruto",
    name: "Naruto Uzumaki",
    series: "Naruto",
    role: "The Nine-Tails Seventh Hokage of the Leaf",
    blurb: "Ostracized as a child carrying a demonic seal, Naruto vowed to become leader of his village. By combining his inexhaustible chakra with Sage modes and raw, charismatic logic, he bridged centuries-old divides and brought peace.",
    themeColor: "#F97316",
    motif: "影",
    stats: {
      power: 96,
      speed: 94,
      technique: 92,
      popularity: 97,
    },
    img: "/src/assets/images/naruto_hokage_1781361762442.jpg",
    crestSymbol: "NINETAILS",
  },
  {
    id: "sasuke",
    name: "Sasuke Uchiha",
    series: "Naruto",
    role: "The Shadow Avenger of the Sharingan Eye",
    blurb: "The sole survivor of his clan, Sasuke walked the path of absolute revenge, mastering the Sharingan eye and violet lightning. Now guarding the Leaf from the shadows, he remains an undefeated rival with godlike visual prowess.",
    themeColor: "#6366F1",
    motif: "瞳",
    stats: {
      power: 95,
      speed: 96,
      technique: 96,
      popularity: 93,
    },
    img: "/src/assets/images/sasuke_rinnegan_1781361777419.jpg",
    crestSymbol: "SHARINGAN",
  },
  {
    id: "saitama",
    name: "Saitama",
    series: "One Punch Man",
    role: "The bored hero who conquers with a single punch",
    blurb: "After three years of intense physical training, Saitama gained power beyond comprehension, losing his hair and all combat thrill in the process. He obliterates city-leveling threats with basic, casual swings.",
    themeColor: "#EAB308",
    motif: "拳",
    stats: {
      power: 100,
      speed: 100,
      technique: 60,
      popularity: 94,
    },
    img: "/src/assets/images/saitama_serious_1781361791789.jpg",
    crestSymbol: "BALD_CAPE",
  },
  {
    id: "tanjiro",
    name: "Tanjiro Kamado",
    series: "Demon Slayer",
    role: "The compassionate slayer wielding Sun Breathing",
    blurb: "A kindhearted boy who picked up the sword only to cure his demonized sister. Inheritor of the lost Sun Breathing dance, his absolute empathy guides his blade, delivering mercy even to the most monstrous demons.",
    themeColor: "#0D9488",
    motif: "炭",
    stats: {
      power: 88,
      speed: 89,
      technique: 93,
      popularity: 94,
    },
    img: "/src/assets/images/tanjiro_sun_1781361810928.jpg",
    crestSymbol: "HINOKAMI",
  },
  {
    id: "levi",
    name: "Levi Ackerman",
    series: "Attack on Titan",
    role: "Humanity's Strongest Soldier inside the walls",
    blurb: "The highly efficient captain of the Special Operations Squad, Levi navigates vertical space like a spinning razor. Despite carrying the heavy grief of lost squads, he cuts through towering Titans with cold, terrifying speed.",
    themeColor: "#64748B",
    motif: "翼",
    stats: {
      power: 91,
      speed: 98,
      technique: 97,
      popularity: 96,
    },
    img: "/src/assets/images/levi_ackerman_1781361823645.jpg",
    crestSymbol: "FREEDOM",
  },
  {
    id: "sukuna",
    name: "Ryomen Sukuna",
    series: "Jujutsu Kaisen",
    role: "The brutal four-armed King of Curses",
    blurb: "An absolute tyrant from the golden age of jujutsu, Sukuna rules with raw slaughter and invisible cuts. He views all creation through the lens of pure hunger, carving mountains and domains with demonic detachment.",
    themeColor: "#991B1B",
    motif: "呪",
    stats: {
      power: 98,
      speed: 96,
      technique: 98,
      popularity: 95,
    },
    img: "/src/assets/images/sukuna_curse_1781361837557.jpg",
    crestSymbol: "SCHISM",
  },
  {
    id: "ichigo",
    name: "Ichigo Kurosaki",
    series: "Bleach",
    role: "The hybrid substitute Soul Reaper",
    blurb: "A high-school student born of Soul Reaper, Quincy, and Hollow blood lines. Wielding the colossal, obsidian Zangetsu sword, he unleashes jet-black reiatsu to shatter fate, fighting solely to protect his friends.",
    themeColor: "#D97706",
    motif: "死",
    stats: {
      power: 96,
      speed: 95,
      technique: 89,
      popularity: 92,
    },
    img: "/src/assets/images/ichigo_bankai_1781361853625.jpg",
    crestSymbol: "BANKAI",
  },
  {
    id: "kaneki",
    name: "Ken Kaneki",
    series: "Tokyo Ghoul",
    role: "The tragic half-ghoul One-Eyed King",
    blurb: "Following a near-death transplant, literature student Kaneki was thrust into the cannibalistic underground. Forced to choose between humanity and survival, he accepted his monstrous side, sprouting crystalline centipede tentacles.",
    themeColor: "#374151",
    motif: "喰",
    stats: {
      power: 90,
      speed: 91,
      technique: 90,
      popularity: 91,
    },
    img: "/src/assets/images/kaneki_ghoul_1781361871082.jpg",
    crestSymbol: "CENTIPEDE",
  },
  {
    id: "elric",
    name: "Edward Elric",
    series: "Fullmetal Alchemist",
    role: "The steel-automail Fullmetal Alchemist",
    blurb: "The youngest State Alchemist in history, Edward paid a devastating physical toll to clasp hands with the Truth. Crafting weapons and structures without drawing transmutation circles, he searches for absolute redemption.",
    themeColor: "#991B1B",
    motif: "鋼",
    stats: {
      power: 87,
      speed: 88,
      technique: 96,
      popularity: 93,
    },
    img: "/src/assets/images/edward_alchemist_1781361887558.jpg",
    crestSymbol: "REDEMPTION",
  },
  {
    id: "light",
    name: "Light Yagami",
    series: "Death Note",
    role: "The self-proclaimed god 'Kira' of the notebook",
    blurb: "A brilliant student who stumbles upon a notebook that kills anyone whose name is written in it. Crafting elaborate tactical nets to evade international police and the genius detective L, he attempts to forge a crime-free utopia.",
    themeColor: "#450A0A",
    motif: "新",
    stats: {
      power: 65,
      speed: 75,
      technique: 99,
      popularity: 91,
    },
    img: "/src/assets/images/light_kira_1781361903060.jpg",
    crestSymbol: "JUSTICE",
  },
  {
    id: "lelouch",
    name: "Lelouch vi Britannia",
    series: "Code Geass",
    role: "The mastermind rebel 'Zero' wielding the Geass",
    blurb: "A banished imperial prince who acquires the power of absolute command. Orchestrating a planetary revolution as a masked outlaw, he manipulates global tactical battles like a chess board, offering up his own life for a kinder future.",
    themeColor: "#581C87",
    motif: "眼",
    stats: {
      power: 70,
      speed: 80,
      technique: 99,
      popularity: 93,
    },
    img: "/src/assets/images/lelouch_geass_1781361919148.jpg",
    crestSymbol: "REBELLION",
  },
];
